# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Download SL
      run: curl https://cdn.shiftleft.io/download/sl >./sl && chmod a+rx ./sl
    - name: Auth SL
      run: ./sl auth --no-diagnostic --org "467bc091-089e-48fc-a948-18c9786b1fc9" --token ""
    - name: Analyze
      run: ./sl analyze --app vulnado --java target/vulnado-0.0.1-SNAPSHOT.jar
    - name: Get Details
      run: curl https://www.shiftleft.io/api/v4/orgs/467bc091-089e-48fc-a948-18c9786b1fc9/apps/vulnado/findings?severity=critical -H "Authorization:Bearer " | grep '\"id\"\|\"title\"' > sl.out
    - name: Print Details
      run: sed 1,1d sl.out
